# pyproject.toml
[build-system]
requires = [
  "setuptools>=61.0",
  "wheel",
  "numpy>=1.20",          # must match or exceed your scikit-learn’s NumPy requirement
]
build-backend = "setuptools.build_meta"
